### PR TITLE
Migrate to AAPT2 for compatibility with Android 14 QPR2

### PR DESCRIPTION
**Pull request by Mahmud0808**
Changes:
- Removed embedded framework workaround.
- Migration to AAPT2 due to issues with AAPT on Android 14 QPR2 and later builds.

The `QuickSwitch.apk` app also uses aapt, which you can find inside its assets folder. This means we need to update this app too. But since I don't have the source code, I can't do that.

### CODE REVIEW

**Comment by devlocalhost** [comment]
Hi, does this fix the issues with android 14 QPR2 roms?

**Comment by Mahmud0808** [comment]
> Hi, does this fix the issues with android 14 QPR2 roms?

Module part should work, APK doesn't because that needs to be updated too. And APK is closed source afaik.

**Comment by devlocalhost** [comment]
> > Hi, does this fix the issues with android 14 QPR2 roms?
> 
> Module part should work, APK doesn't because that needs to be updated too. And APK is closed source afaik.

So it needs more work? Would maybe using the quickswitch command work?

I really want to get rid of trebuchet, I hate it.

**Comment by Mahmud0808** [comment]
> Would maybe using the quickswitch command work?

Give it a try

**Comment by devlocalhost** [comment]
> > Would maybe using the quickswitch command work?
> 
> Give it a try

Well I tried to do something, I downloaded the changes you did and flashed the module, but no success:

```
# /data/adb/modules/quickswitch/quickswitch --ch=app.lawnchair          
       _____
   __ |     | __
  |  ||     ||  |
  |  ||     ||  |
  |__||     ||__|
      |_____|
    QuickSwitch

 The Lawnchair Team


The overlay will be copied to /data/adb/modules/quickswitch/product/overlay/QuickSwitchOverlay...
/data/adb/modules/quickswitch/zipsigner[19]: syntax error: unexpected '||'
cp: cannot stat '/data/adb/modules/quickswitch/signed.apk': No such file or directory

Overlay successfully copied...

Setting permissions...

Logs copied to /sdcard/Documents/quickswitch...

Please reboot for changes to take effect.
```

**Comment by Mahmud0808** [comment]
> /data/adb/modules/quickswitch/zipsigner[19]: syntax error: unexpected '||'
> cp: cannot stat '/data/adb/modules/quickswitch/signed.apk': No such file or directory

You need PR #57 too

**Comment by skittles9823** [comment]
merged in #60

**Pull request closed without merging**
