### PR TITLE
Script fixes and Apatch support. Merging #54 and #57

### PR DESCRIPTION
**Pull request by j7b3y**
Tested by Apatch+Android14-QPR2 & KernelSU+Android13.

Including #54  and #57 

1. Fixed the script.
When $KSU was empty during installation, the process to delete KSU=true from "quickswitch" was not performed correctly.
As a result, a non-KSU user had to manually exclude her KSU=true statement from "quickswtch" before running the script.

2. Added Apatch to solution options.
Apatch busybox and Apatch version are automatically acquired when APATCH=true.
The variable APATCH=true in the script will be automatically removed if APATCH cannot be detected during module installation.
I remember that the Apatch Module mechanism is based on kernelsu. Therefore, other processing follows kernelsu.

3. Copy only aapt2 that fits your architecture to $MODPATH.
Copy only aapt2 whose name includes arch obtained with ```getprop ro.product.cpu.abi``` to $MODPATH.

With APatch and KernelSU,
When you run ```[ "$($MODPATH/common/aapt2_arm64-v8a version)" ] && AAPT2=aapt2_arm64-v8a```, the result of the first command is returned empty and the empty variable is set to AAPT2.
As a result, all aapt2 binaries in the common dir are copied to the $MODPATH/aapt2 dir.

Android 13 worked without any problems. 
However, with Android 14-QPR2, while the system's Resent is no longer used, it's unclear whether Lawnchair is functioning as expected because it crashes.

### CODE REVIEW

**Comment by DiamivaeBro** [comment]
Hm,ive tried to install module with this commits

**Comment by j7b3y** [comment]
There was an overlay problem with Apatch, so I fixed it and it seems to be working fine on my device.

I found an unofficial QPR2 build of Lawnchair on Telegram, so I'm using it.

**Comment by AlexS2412** [comment]
Screenshot_20240618-192706_QuickSwitch
doesnt work on oriole pixel 6 derpfest android 14.

**Comment by j7b3y** [comment]
This commit only modifies the script and does not change the app.
To use it, grant permissions to termux and then run the following command.
```
su -c /data/adb/modules/quickswitch/quickswitch --ch=<launcher.package.name>
```

Since QuickSwitch.apk is closed source, there is a high chance that nothing can be done unless the app developer takes action.

**Pull request merged**
